name: "🐛 Bug report"
description: Report errors or unexpected behavior in this product
title: "[Bug]"
labels:
  - "type: bug"
body:
  - type: input
    attributes:
      label: Version?
      placeholder: 1.0.0
      description: The version of product which caused the issue.
    validations:
      required: true

## ONLY USED IN CASE OF SELENIUM
#  - type: dropdown
#    attributes:
#      label: Browser?
#      description: Which Browser caused the issue?
#      multiple: false
#      options:
#        - Chrome
#        - Firefox
#        - IE
#        - Edge
#        - Safari
#        - Other
#        - Not Required
#    validations:
#      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: We highly suggest including a screenshots and a bug report log (GitHub Gist link).
      placeholder: Tell us the steps required to trigger your bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: true

  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: true